apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pod-test-2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache-web-server-1
        image: jonlangemak/web_server_1
        ports:
        - containerPort: 80
          name: web-tcp-80
          protocol: TCP
      - name: apache-web-server-2
        image: jonlangemak/web_server_2
        ports:
        - containerPort: 80
          name: web-tcp-80
          protocol: TCP
